name: Unit Tests (PHPUnit)
on: push

jobs:
  phpunit:
    name: "PHP ${{ matrix.php-version }} (${{ matrix.deps }})"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        deps:
          - "highest"
        include:
          - php-version: "8.2"
            deps: "lowest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: gmp, mbstring
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.deps }}

      - name: Run PHPUnit
        run: vendor/bin/phpunit --fail-on-skipped
